###################
### 数据库配置 ###
###################
main:
  host: 127.0.0.1
  port: 3306
  username: alopex
  password: alopex
  database: alopex
  charset: utf8
  parseTime: true
  loc: Local
platform_qp:
  host: 127.0.0.1
  port: 3306
  username: qp
  password: qp
  database: qp
  charset: utf8
  parseTime: true
  loc: Local



