###################
### 数据库配置 ###
###################
# Mysql配置
mysql:
  main_db:
    host: 127.0.0.1
    port: 3306
    username: allSysPlatDb
    password: allSysPlatDb
    database: maindb
    charset: utf8
    parseTime: true
    loc: Local
  games_db:
    qp:
      host: 127.0.0.1
      port: 3306
      username: ckgame
      password: ckgame
      database: ckgame
      charset: utf8
      parseTime: true
      loc: Local
# SQLite配置
sqlite:
  a: data/app.db



