###################
### 数据库配置 ###
###################
# Mysql配置
mysql:
  main_db:
    host: 127.0.0.1
    port: 3306
    username: root
    password: root
    database: ckgame
    charset: utf8
    parseTime: true
    loc: Local
  games_db:
    qp:
      host: 127.0.0.1
      port: 3306
      username: root
      password: root
      database: maindb
      charset: utf8
      parseTime: true
      loc: Local
# SQLite配置
sqlite:
  a: true
  b: sdfsdfs



